### PR TITLE
Use task to run listen command

### PR DESCRIPTION
**Pull request by vcheung-stripe**
This uses a vscode task to run the `stripe listen` command, allowing us to leverage the built-in escaping features for the shell input: https://code.visualstudio.com/api/references/vscode-api#ShellQuotedString

### CODE REVIEW

**Review by charliecruzan-stripe — CHANGES_REQUESTED** [review]
nice! i think this means we can delete the `shellEscape.ts` and `shellEscape.test.ts` files?

**Comment by vcheung-stripe** [comment]
Yeah I think so, will do

**Review by charliecruzan-stripe — APPROVED** [review]

**Review by charliecruzan-stripe — APPROVED** [review]

**Comment by bernardoamc-stripe** [comment]
This seems in line with what I was thinking. 👏 Do we have a way to test this with the researcher input?

**Comment by vcheung-stripe** [comment]
@bernardoamc-stripe I've tried it out with the examples we've seen and they work insofar as they get quoted as expected.

**Pull request merged**
