### PR TITLE
Create Express Webhook Handler Snippet

### LINKED ISSUE #73: Add code snippet for webhooks validation in JavaScript
Add code snippet for webhooks validation in JavaScript.

Turn this code example into a meaningful snippet

```javascript
// This example uses Express to receive webhooks
const app = require('express')();

// Use body-parser to retrieve the raw body as a buffer
const bodyParser = require('body-parser');

// Match the raw body to content type application/json
app.post('/webhook', bodyParser.raw({type: 'application/json'}), (request, response) => {
  let event;

  try {
    event = JSON.parse(request.body);
  } catch (err) {
    response.status(400).send(`Webhook Error: ${err.message}`);
  }

  // Handle the event
  switch (event.type) {
    case 'payment_intent.succeeded':
      const paymentIntent = event.data.object;
      // Then define and call a method to handle the successful payment intent.
      // handlePaymentIntentSucceeded(paymentIntent);
      break;
    case 'payment_method.attached':
      const paymentMethod = event.data.object;
      // Then define and call a method to handle the successful attachment of a PaymentMethod.
      // handlePaymentMethodAttached(paymentMethod);
      break;
    // ... handle other event types
    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  // Return a response to acknowledge receipt of the event
  response.json({received: true});
});

app.listen(8000, () => console.log('Running on port 8000'));
```

### PR DESCRIPTION
**Pull request by pepin-stripe**
Fixes #73 

This adds a Snippet to generate a webhook events handler for Express.js. 

Copy feedback greatly appreciated \o/

### CODE REVIEW

**Review by vcheung-stripe — DISMISSED** [review]
I think it looks great, but I'd like to know what @auchenberg-stripe thinks.

**Comment by auchenberg-stripe** [comment]
Generally we want to encourage developers to do signature checking of their webhooks, so we use the more complete code example from https://stripe.com/docs/payments/handling-payment-events#signature-checking and turn into the snippet.

Copy looks great @pepin-stripe

**Comment by pepin-stripe** [comment]
Sounds good, I'll update the snippet!

**Review by vcheung-stripe — APPROVED** [review]

**Comment by pepin-stripe** [comment]
ptal @auchenberg-stripe

**Review by auchenberg-stripe — APPROVED** [review]

**Pull request merged**
